Hw05 parallel execution
PrideSt/otus-golang pull request #5
Opened 2020-08-23 13:35 UTC by PrideSt

## Домашнее задание №5 «Параллельное исполнение»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-08-24 17:14 UTC, kulti reviewed
Довольно сложное и запутанное решение. И не очень похоже на Go. Предлагаю, попробовать переписать это в Go-парадигме.

1. Убрать все абстракции-типы (сторадж, мастер, воркер) и обойтись стандартными типами.
1. Для взаимодействия завести один канал для задач - Run пишет в этот канал, воркеры из него читают. Если канал закрыть, то воркеры выйдут.
1. Для обратной связи об ошибках использовать другой канал или атомик.

В итоге:
Сторадж - это []Task.
Мастер - это горутина Run.
Воркер - это горутина с простым циклом `for task := range taskCh { ... }`.

2020-08-24 17:14 UTC, kulti commented on hw05_parallel_execution/run.go
> +			w.chReady <- w
Не очень чистый и понятный код работы с chReady.

Запись здесь, а закрытие в master'e. Неочевидно, что проблем не будет и не произойдет записи в закрытый канал.

2020-08-24 17:14 UTC, kulti commented on hw05_parallel_execution/run.go
> +			}
С select есть нюанс, что если оба case готовы к работе, то выбирается случайно. Чисто теоретически stop может долго не выбираться. Рекомендую использовать такой паттерн:
```
select {
  case <-stopCh:
    return
  default:
}

select {
  case <-stopCh:
    return
  case ...:
    ...
}
```

2020-09-09 19:26 UTC, PrideSt commented on .golangci.yml
> +    local-prefixes: github.com/PrideSt/otus-golang
Спасибо

2020-09-09 19:27 UTC, PrideSt commented on hw05_parallel_execution/run_test.go
> +		require.Nil(t, result)
поправил

2020-09-09 19:27 UTC, PrideSt commented on hw05_parallel_execution/run.go
> +			w.chReady <- w
сделал простую реализацию

2020-09-09 19:28 UTC, PrideSt commented on hw05_parallel_execution/run.go
> +			}
Спасибо, уже применял это в последующих домашках

2020-09-11 19:43 UTC, kulti requested changes
Теперь решение намного лучше, т.к. простое и понятное. Осталось починить запуск лишних горутин и откатить изменения в тестах, т.к. гонок быть не должно. Также можно почистить код по замечаниям для максимального балла.

2020-09-11 19:43 UTC, kulti commented on hw05_parallel_execution/run.go
> +			go func() {
Получается, что горутин будет столько, сколько len(tasks), а не grtnCnt.

Одновременных горутин, конечно, будет не больше grtnCnt, только это довольно расточительно запускать каждый раз новую горутину, если можно просто в начале запустить нужное количество горутин с общим каналом для задач. И не придется придумывать механизм, ограничивающий количество одновременных горутин.

2020-09-11 19:43 UTC, kulti commented on hw05_parallel_execution/run.go
> +		if errLimit < 0 || errLimitInt32 > atomic.LoadInt32(&errCnt) {
Два разных errLimit — странно смотрится. Как вариант, можно удалить errLimitInt32 и здесь всегда писать `int32(errLimit) > ...`.

2020-09-11 19:43 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +	t.Run("negative of zero goroutine count", func(t *testing.T) {
Было бы симпатичнее этот тест на два разбить. Либо назвать его "invalid goroutine count", а внутри еще раз использовать t.Run для двух сабтестов zero и negative.

2020-09-11 19:43 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		require.Equal(t, tasksCount, int(atomic.LoadInt32(&runTasksCount)))
Если Run работает корректно, то он он дожидается остановки всех горутин. Т.е. никаких параллельных записей в runTasksCount здесь быть не может. Поэтому в других тестах и не было atomic.LoadInt32.

Надо было искать ошибку в Run. Сейчас, судя по всему, все в порядке - не вижу, как Run может чего-то не дожидаться и тесты работают под рейсом, если убрать atomic.LoadInt32.

Это изменение нужно откатить.

2020-09-11 19:43 UTC, kulti commented on hw05_parallel_execution/run.go
> +		return ErrErrorsLimitExceeded
В длинном теле if'a стоит continue, а потом сразу return — явно признак, что что-то переусложненно.

Если переписать условие на обратное, то код станет чище и проще:
```
	for _, task := range tasks {
		if errLimit >= 0 && atomic.LoadInt32(&errCnt) >= errLimitInt32 {
			return ErrErrorsLimitExceeded
		}
		...
	}
```

2020-09-14 19:50 UTC, PrideSt commented on hw05_parallel_execution/run.go
> +		if errLimit < 0 || errLimitInt32 > atomic.LoadInt32(&errCnt) {
избавился в новой реализации от конкурентного доступа к счетчику

2020-09-14 19:50 UTC, PrideSt commented on hw05_parallel_execution/run_test.go
> +	t.Run("negative of zero goroutine count", func(t *testing.T) {
разбил на 2 теста

2020-09-14 20:01 UTC, PrideSt commented on hw05_parallel_execution/run_test.go
> +		require.Equal(t, tasksCount, int(atomic.LoadInt32(&runTasksCount)))
> Надо было искать ошибку в Run. Сейчас, судя по всему, все в порядке - не вижу, как Run может чего-то не дожидаться и тесты работают под рейсом, если убрать atomic.LoadInt32.

Я и пытался найти ошибку в Run, data race наблюдался на версии кода, представленной на ревью, за исключением atomic.LoadInt32 в тестах. Всю дорогу в тестах у меня был включен `goleak.VerifyNone(t)` и судя по трейс дампу хвостов в Run не оставалось, это и вызвало у меня недоумение. Будет интересно это подебажить, но сейчас времени на это нет.

Изменения в тестах касательно атомарности чтения runTasksCount откатил. В новой версии проблема не наблюдается.

2020-09-14 20:03 UTC, PrideSt commented on hw05_parallel_execution/run.go
> +			go func() {
В новой реализации горутин создается строго необходимое кол-во. Возможно стоит конкретизировать постановку задачи.

2020-09-14 20:10 UTC, PrideSt commented on hw05_parallel_execution/run.go
> +		return ErrErrorsLimitExceeded
Да, недосмотрел что можно инвертировать условие. В новой реализации примерно в таком виде оно и используется

2020-09-15 16:33 UTC, kulti commented on hw05_parallel_execution/run.go
> +		for !isPushed {
Не сразу понял, что за `isPushed`. Можно обойтись без вложенного цикла, например, так:
```
i := 0
for i < len(tasks) {
    ...
    case chTasks <- tasks[i]:
        i++
    }
}

2020-09-15 16:33 UTC, kulti commented on hw05_parallel_execution/run.go
> +		return fmt.Errorf("%w: expected >1, actual %d", ErrInvalidGrtnCnt, grtnCnt)
`expected >= 1` — неаккуратненько.

2020-09-15 16:33 UTC, kulti commented on hw05_parallel_execution/run.go
> +			go func() {
Да, спасибо. Подумаем над формулировкой.

2020-09-15 16:33 UTC, kulti commented on hw05_parallel_execution/run_test.go
> +		require.Equal(t, tasksCount, int(atomic.LoadInt32(&runTasksCount)))
Хм... В версии, которая была на ревью я гонки не видел и запускал в цикле тесты под рейсом (убрав atomic.LoadInt32). Все было ок.

А рейс вы видели только локально или на CI тоже есть упавшая джоба? На CI можно посмотреть хэш коммита, на котором падало, и попробовать разобраться.

2020-09-15 16:33 UTC, kulti approved these changes
Теперь все верно. ДЗ принято — 10/10.

2020-09-15 19:10 UTC, PrideSt commented on hw05_parallel_execution/run_test.go
> +		require.Equal(t, tasksCount, int(atomic.LoadInt32(&runTasksCount)))
падало локально, в ci не пробовал пушить

2020-09-15 19:14 UTC, PrideSt commented on hw05_parallel_execution/run.go
> +		for !isPushed {
о таком варианте я что-то не подумал, круто!

2020-09-15 19:32 UTC, PrideSt commented on hw05_parallel_execution/run.go
> +		for !isPushed {
поправил

2020-09-15 19:32 UTC, PrideSt commented on hw05_parallel_execution/run.go
> +		return fmt.Errorf("%w: expected >1, actual %d", ErrInvalidGrtnCnt, grtnCnt)
да, ошибся. Поправил

2020-09-15 19:32 UTC, merged